### PR TITLE
Faster force close

### PR DESCRIPTION
**Pull request by LoneDev6**
Now Force close option is 100% faster than before

### CODE REVIEW

**Comment by cursey** [comment]
Why not use `ExitProcess`? Opening a handle to the current process seems really strange.

**Comment by LoneDev6** [comment]
It used to be exit(0) before my commit and it was really slow.
Maybe ExitProcess is faster, I didn't test that

**Comment by cursey** [comment]
Could you test it? Like I said something about opening a handle to the process you're already running in just to close it seems really strange to me. You generally only ever open a handle to a process if you're interacting with a process that isn't your own. If `ExitProcess` is just as fast as `TerminateProcess` I would prefer to use it, but if it's not then I'll be happy to merge this change the way it is.

**Comment by LoneDev6** [comment]
Tested, ExitProcess is as fast as TerminateProcess

**Pull request merged**
