### PR TITLE
FOV fix + current aggro target

### PR DESCRIPTION
**Pull request by kleric**
displays what the character is currently aggroing

useful for Song of Grief if you want to see who should desummon pet/crisis

### CODE REVIEW

**Comment by cursey** [comment]
Since `Mabinogi.hpp` is autogenerated from ReClass.NET it would be nice if you included the updated `mabi.rcnet` file.

**Comment by kleric** [comment]
Sorry I don't actually/didn't use ReClass.NET, how would I do that?

**Comment by cursey** [comment]
No worries, I'll make the changes.

**Comment by kleric** [comment]
Thanks, sorry to make you do that! :(

**Pull request merged**
