### PR TITLE
[WIP] Cursor Unhide for Chain skills, need help

### PR DESCRIPTION
**Pull request by Aahzmandius**
#48 @Iuke121 was able to find the address/edit to skip hiding the 2D cursor for chain skills, using the (currently working) version from the koorimio mod, however it still doesn't work. I tried as a simple patch in Patches.json, and then tried it as an early "time critical" mod alongside the data folder change, just in case the cursor is some kind of engine thing that needs to be jmped early for whatever reason. Still no luck.

Intended result, using koorimio.dll: 
image

Current result, glitchy at best and only while moving, under certain crazy circumstances, rapidly blinking on/off: https://webmshare.com/play/y691B

### CODE REVIEW

**Comment by cursey** [comment]
Just hook `ShowCursor` and make it do nothing https://docs.microsoft.com/en-us/windows/desktop/api/winuser/nf-winuser-showcursor

**Comment by cursey** [comment]
I just sort of assumed if they were hiding the cursor they were using `ShowCursor`. Maybe they're not hiding it and instead just changing the cursor to a blank image? Try hooking `SetCursor`? I can actually take a look at what they're doing if that doesn't work.

**Comment by AfroZenPizza** [comment]
Probably should have put that in the original post but I was being lazy on my phone.

What I've tried hooking with no luck:

User32:
LoadImage(A and W)
LoadCursor(A and W)
SetCursor
Show Cursor /obviously/

D3D9 
ShowCursor - vtable 12
SetCursorProperties - vtable 10

Getting addresses that make sense all the functions, but none of the hooks fire. It may be something related to Corsair keyboard and mouse as I've noticed DirectInput doesn't catch the Corsair mouse but does catch a Logitech wireless. I've had some strange issues with the way that Corsairs CUE works. 

Thanks for the follow up. Not really sure where to chase this anymore. Thought you might know more as it seems you have spent more time on this than I have.

**Comment by cursey** [comment]
I havn't spent any time on this feature in particular. I can just take a look at what the game is doing when I get the time. Thanks for trying all the obvious avenues first though!

**Pull request closed without merging**
