### PR TITLE
CC on numpad press

### PR DESCRIPTION
**Pull request by PoiDoe**
attempt at adding cc on Numpad press to the autochangechannel mod

there is most likely a better way of doing this but this is my half-assed still learning how to do programming attempt.

It does appear to work, however, the hotkey appears to be global so if using multiclient and pressing hotkey all clients will cc.

### CODE REVIEW

**Comment by PoiDoe** [comment]
Correction, it only works on the last client opened

**Comment by cursey** [comment]
Would you like to know how to make it only work on the active client?

**Comment by PoiDoe** [comment]
Yes please

I was trying to work out how to get it to trigger off alt + numpad too but had no luck.

**Comment by cursey** [comment]
Alright, so I had to actually improve the DInput hook to make this easy. In the recent commit 62ab0f26f6d60a2bd3c0e6135770cb4bae6386c5 `Mod`'s now have an `onKeyDown` and `onKeyUp` virtual method that you can implement. Here is an example of one for `AutoChangeChannels` to give you an idea of how to implement your idea specifically.
```
void AutoChangeChannels::onKeyUp(DWORD key) {
    if (key == DIK_HOME) {
        auto game = g_kanan->getGame();
        game->changeChannel(1);
    }
}
```
Let me know if you have any questions.

**Comment by PoiDoe** [comment]
oh thank you for adding this function. I'll work on improving the code then possibly adding a new pull request cause I think these a group of people that want this kinda thing.

thanks again tho. your great!

**Pull request closed without merging**
