### PR TITLE
Add Ego Auto Select x30

### PR DESCRIPTION
**Pull request by kohupallintrax**
Add Ego Auto Select x30 to speedup patches and Enable prop target with skills loaded quality of life patches in patches.json

### CODE REVIEW

**Comment by kohupallintrax** [comment]
Ah interesting - I can review it some more. I was curious as to why the code was structured the way it was and I suppose that answers my question. I appreciate the feedback and testing as the character I was using doesn't have access to fateweaver.

**Comment by cursey** [comment]
Should I hold on merging this?

**Comment by kohupallintrax** [comment]
Yes, hold on merge. I'll work some folks that have access to the skill and I'll see if I can make it work as intended in more situations.

**Comment by kohupallintrax** [comment]
Patch has been updated and we are good to merge @cursey . Tested the aforementioned issues. New patch now works with fateweaver correctly (verified ability to target both players and mobs with CTRL while retaining ability to target props). New patch works with healing as expected (Able to target allies, unable to target mobs with CTRL).

Thank you for testing the edge cases I hadn't @3nv0y - Was running dungeons with it throughout today with most the skillsets I use but you have covered my blind spots.

**Comment by cursey** [comment]
Good work. Thanks for the contribution!

**Pull request merged**
