### PR TITLE
Update more mods broken on 8/10/23

### LINKED ISSUE #302: Alternative "Alt Text" Mod
Several updates ago, a Mabinogi update broke the Kanan mod that allowed you to change the text color that you would see over players/NPCs heads from the current dark blue to any color hue you could pick on a color wheel. This has yet to be re-enabled in what I believe has been a years time.  

Is this mod completely obsoleted and cannot be fixed? I loved this mod as the dark blue on transparent black text has always been incredibly hard for me to read normally.

### PR DESCRIPTION
**Pull request by kohupallintrax**
Update the patch and pattern for allow interface while dead. 

Update pattern for color alt text. Fixes #302 

Update don't close title window

### CODE REVIEW

**Review by bastcatalan — APPROVED** [review]
typo fixes on cooking mod, everything looks good, no sus changes

**Comment by kohupallintrax** [comment]
Is Github incentivizing PR reviews now? lol

**Comment by shaggyze** [comment]
> Is Github incentivizing PR reviews now? lol

I don't think so, just a new user who thinks he's helping by approving your PR's and pointing out the obvious..
maybe he doesn't know he needs write access for reviews to matter.

**Review by cursey — APPROVED** [review]
LGTM

**Pull request merged**
