### PR TITLE
fix cooking mod for x64, expose call api for FunctionHook

### PR DESCRIPTION
**Pull request by lask3802**
Fix cooking mod for x64 with FunctionHook method instead of asm. For the convenience of implementation, I have exposed CallOriginal in FunctionHook. Also cleanup unnecessary code in CookingMod

### CODE REVIEW

**Review by Byteretention — COMMENTED** [review]
Fixes the issues with using raw ASM and works just fine. thanks for updating this for me. don't really have the time to maintain my stuff currently

**Comment by lask3802** [comment]
MSVC does not support inline ASM for the x64 platform, which can be a bit frustrating. To write in ASM, we need to write in a separate .asm file. I think using function hooks to avoid the use of ASM files seems to be more suitable for the overall style of the project.

**Comment by Byteretention** [comment]
There was a plan to use xbyak(https://github.com/herumi/xbyak)
but no one has really had the time to add it in yet

**Review by Byteretention — APPROVED** [review]

**Comment by lask3802** [comment]
Wow JIT asm with native C++ syntax. That's a genius lib

**Review by cursey — APPROVED** [review]
LGTM

**Pull request merged**
