### PR TITLE
Update Equipment Override to include 6 Dye Spots

### PR DESCRIPTION
**Pull request by y3tii**
image

### CODE REVIEW

**Comment by y3tii** [comment]
Looks like Color 4, 5 and 6 are 4 bytes off, I'll fix that now.

**Comment by y3tii** [comment]
I've added the extra dye spots to the Item List, and made the Mabinogi.rcnet file, but for the Equipment Override.
In EquipmentOverride.cpp I'm running into this issue.
image
I can't really see what's causing it, so any help would be appreciated! ^^

**Comment by Aahzmandius** [comment]
I vaguely remember a comment from Rydian saying some of the new clothes skip over 4th color entirely for some reason. Just a heads up depending on what you're testing.

**Comment by y3tii** [comment]
Ahh yes thanks Aahz.
image
This is all the dye spots in the correct places. In Mabinogi.rcnet I have added the 6 dye spots to the Item List and Equipment Info. There is a 4 byte gap between spot 3 and 4.

image
When I set something to color[3] it fails. So I skipped it and started again at color[4].
This miiiight be because of the gap, but skipping color[3] it does work so for now I will push the updated files.

**Comment by y3tii** [comment]
Oh yea, I'm not sure if this should be changed as well, just a heads up.
image

**Comment by y3tii** [comment]
Ok, realised the No Flashy mod only worked on clothes that are already flashy, and it also skips color[3] so I've fixed that above.

All working good now ^^

**Pull request merged**
